# Generated by Django 5.0 on 2024-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEmissionRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('emission_rate', models.FloatField()),
                ('green_house_contribution', models.FloatField()),
            ],
            options={
                'db_table': 'category_emission_rates',
            },
        ),
    ]
