# Generated by Django 5.0 on 2024-01-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.JSONField(blank=True, default=dict, help_text='Reason for disabling the key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Developer Key',
                'verbose_name_plural': 'Developer Keys',
                'db_table': 'dev_key',
                'ordering': ['-created_at'],
            },
        ),
    ]
